# Generated by Django 4.0.4 on 2022-05-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Présentielle', 'Présentielle'), ('Distantielle', 'Distantielle')], max_length=45)),
                ('description', models.CharField(max_length=300)),
                ('traitement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('specialite', models.CharField(choices=[('General', 'General'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Diagnostic radiology', 'Diagnostic radiology'), ('Medical genetics', 'Medical genetics'), ('Internal medicine', 'Internal medicine')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('dateNaissance', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenderVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('anuuler', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allout_souhaib.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allout_souhaib.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allout_souhaib.patient')),
            ],
        ),
    ]
