# Generated by Django 4.0.4 on 2022-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allout_souhaib', '0003_remove_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendervous',
            name='anuuler',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
